export { Header } from "./Header";
export { Footer } from "./Footer";
export { default as SimpleHero } from "./SimpleHero";
export { default as ListBasedNews } from "./ListBasedNews";
export { default as MinimalNav } from "./MinimalNav";
export { MinimalNavbar } from "./MinimalNavbar";
export { default as BorderlessGallery } from "./BorderlessGallery";
export { default as CleanContactForm } from "./CleanContactForm";
export { default as MicroInteractions } from "./MicroInteractions";
export { default as CleanFooter } from "./CleanFooter";
export { default as MinimalFooter } from "./MinimalFooter";
export { default as MinimalHero } from "./MinimalHero";
export { default as MinimalStats } from "./MinimalStats";
export { default as MinimalAbout } from "./MinimalAbout";
export { default as MinimalPrograms } from "./MinimalPrograms";
export { default as MinimalTestimonials } from "./MinimalTestimonials";
export { default as MinimalCTA } from "./MinimalCTA";
export { MinimalEvents } from "./MinimalEvents";
export { MinimalFaculty } from "./MinimalFaculty";
