export type AdminTheme = {
  id: string;
  name: string;
  mode: "light" | "dark";
  description: string;
  swatches: string[];
  cssVars: Record<string, string>;
};

export const ADMIN_THEMES: AdminTheme[] = [
  {
    id: "classic-light",
    name: "Classic Light",
    mode: "light",
    description: "Netral dengan aksen biru tegas",
    swatches: ["#0f172a", "#2563eb", "#f8fafc"],
    cssVars: {
      background: "#f8fafc",
      foreground: "#0f172a",
      card: "#ffffff",
      "card-foreground": "#0f172a",
      popover: "#ffffff",
      "popover-foreground": "#0f172a",
      primary: "#0f172a",
      "primary-foreground": "#e2e8f0",
      secondary: "#e2e8f0",
      "secondary-foreground": "#0f172a",
      muted: "#e2e8f0",
      "muted-foreground": "#1f2937",
      accent: "#2563eb",
      "accent-foreground": "#f8fafc",
      destructive: "#b91c1c",
      border: "#e2e8f0",
      input: "#e2e8f0",
      ring: "#2563eb",
      sidebar: "#f8fafc",
      "sidebar-foreground": "#0f172a",
      "sidebar-primary": "#2563eb",
      "sidebar-primary-foreground": "#f8fafc",
      "sidebar-accent": "#e0f2fe",
      "sidebar-accent-foreground": "#0f172a",
      "sidebar-border": "#e2e8f0",
      "sidebar-ring": "#2563eb",
    },
  },
  {
    id: "modern-light",
    name: "Modern Light",
    mode: "light",
    description: "Vibran dengan sentuhan cyan",
    swatches: ["#0ea5e9", "#f97316", "#f0f9ff"],
    cssVars: {
      background: "#f0f9ff",
      foreground: "#0f172a",
      card: "#ffffff",
      "card-foreground": "#0f172a",
      popover: "#ffffff",
      "popover-foreground": "#0f172a",
      primary: "#0ea5e9",
      "primary-foreground": "#022c3a",
      secondary: "#ffeede",
      "secondary-foreground": "#7c2d12",
      muted: "#e2e8f0",
      "muted-foreground": "#1e293b",
      accent: "#a855f7",
      "accent-foreground": "#faf5ff",
      destructive: "#b91c1c",
      border: "#dbeafe",
      input: "#dbeafe",
      ring: "#0ea5e9",
      sidebar: "#e0f2fe",
      "sidebar-foreground": "#0f172a",
      "sidebar-primary": "#0ea5e9",
      "sidebar-primary-foreground": "#f8fafc",
      "sidebar-accent": "#fef3c7",
      "sidebar-accent-foreground": "#92400e",
      "sidebar-border": "#dbeafe",
      "sidebar-ring": "#0ea5e9",
    },
  },
  {
    id: "minimalist-light",
    name: "Minimalist",
    mode: "light",
    description: "Monokrom bersih untuk fokus konten",
    swatches: ["#111827", "#9ca3af", "#ffffff"],
    cssVars: {
      background: "#ffffff",
      foreground: "#111827",
      card: "#ffffff",
      "card-foreground": "#111827",
      popover: "#ffffff",
      "popover-foreground": "#111827",
      primary: "#111827",
      "primary-foreground": "#f9fafb",
      secondary: "#e5e7eb",
      "secondary-foreground": "#111827",
      muted: "#f3f4f6",
      "muted-foreground": "#4b5563",
      accent: "#d1d5db",
      "accent-foreground": "#111827",
      destructive: "#b91c1c",
      border: "#e5e7eb",
      input: "#e5e7eb",
      ring: "#d1d5db",
      sidebar: "#f9fafb",
      "sidebar-foreground": "#111827",
      "sidebar-primary": "#111827",
      "sidebar-primary-foreground": "#f9fafb",
      "sidebar-accent": "#e5e7eb",
      "sidebar-accent-foreground": "#0f172a",
      "sidebar-border": "#e5e7eb",
      "sidebar-ring": "#d1d5db",
    },
  },
  {
    id: "midnight-emerald",
    name: "Midnight Emerald",
    mode: "dark",
    description: "Gelap elegan dengan aksen hijau",
    swatches: ["#0f172a", "#10b981", "#0b1120"],
    cssVars: {
      background: "#0b1120",
      foreground: "#e2e8f0",
      card: "#0f172a",
      "card-foreground": "#e2e8f0",
      popover: "#0f172a",
      "popover-foreground": "#e2e8f0",
      primary: "#10b981",
      "primary-foreground": "#052e16",
      secondary: "#1f2937",
      "secondary-foreground": "#e2e8f0",
      muted: "#111827",
      "muted-foreground": "#94a3b8",
      accent: "#22d3ee",
      "accent-foreground": "#0f172a",
      destructive: "#ef4444",
      border: "#1f2937",
      input: "#1f2937",
      ring: "#10b981",
      sidebar: "#0f172a",
      "sidebar-foreground": "#e2e8f0",
      "sidebar-primary": "#10b981",
      "sidebar-primary-foreground": "#052e16",
      "sidebar-accent": "#1e3f35",
      "sidebar-accent-foreground": "#10b981",
      "sidebar-border": "#1f2937",
      "sidebar-ring": "#10b981",
    },
  },
  {
    id: "violet-night",
    name: "Violet Night",
    mode: "dark",
    description: "Kontras tinggi bernuansa ungu",
    swatches: ["#1f1135", "#8b5cf6", "#0b0a10"],
    cssVars: {
      background: "#0b0a10",
      foreground: "#e5defd",
      card: "#120f1d",
      "card-foreground": "#e5defd",
      popover: "#120f1d",
      "popover-foreground": "#e5defd",
      primary: "#8b5cf6",
      "primary-foreground": "#0b0a10",
      secondary: "#1f1135",
      "secondary-foreground": "#e5defd",
      muted: "#1c1a25",
      "muted-foreground": "#c4b5fd",
      accent: "#22d3ee",
      "accent-foreground": "#0b0a10",
      destructive: "#f87171",
      border: "#2d2a3a",
      input: "#2d2a3a",
      ring: "#8b5cf6",
      sidebar: "#120f1d",
      "sidebar-foreground": "#e5defd",
      "sidebar-primary": "#8b5cf6",
      "sidebar-primary-foreground": "#0b0a10",
      "sidebar-accent": "#2e1a3f",
      "sidebar-accent-foreground": "#8b5cf6",
      "sidebar-border": "#2d2a3a",
      "sidebar-ring": "#8b5cf6",
    },
  },
];
