#!/bin/bash

# Phase 1 Post-Setup Database Configuration Guide
# Run this script untuk setup database PostgreSQL dengan cepat

echo "==================================="
echo "Phase 1 - Database Setup Guide"
echo "==================================="
echo ""

echo "📋 LANGKAH 1: Install & Configure PostgreSQL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Option A: Windows (Download)"
echo "  1. Download dari: https://www.postgresql.org/download/windows/"
echo "  2. Install dengan default settings"
echo "  3. Remember password untuk postgres user"
echo ""
echo "Option B: Docker (Recommended)"
echo "  1. Install Docker: https://www.docker.com/products/docker-desktop"
echo "  2. Run: docker run --name sekolix-postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 -d postgres:15"
echo ""

echo "📋 LANGKAH 2: Create Database"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Buka PowerShell atau Command Prompt, jalankan:"
echo "  psql -U postgres -c \"CREATE DATABASE sekolix_db;\""
echo ""
echo "Atau gunakan pgAdmin (GUI yang datang dengan PostgreSQL)"
echo ""

echo "📋 LANGKAH 3: Update Environment Variables"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Edit file: .env.local"
echo ""
echo "Set DATABASE_URL:"
echo "  DATABASE_URL=\"postgresql://postgres:postgres@localhost:5432/sekolix_db\""
echo ""
echo "Generate NEXTAUTH_SECRET:"
echo "  Run: openssl rand -base64 32  (atau gunakan online generator)"
echo ""
echo "Set NEXTAUTH_URL:"
echo "  NEXTAUTH_URL=\"http://localhost:3000\""
echo ""

echo "📋 LANGKAH 4: Sync Database Schema"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run di terminal:"
echo "  npm run prisma:generate"
echo "  npm run prisma:push"
echo ""
echo "Verify di Prisma Studio:"
echo "  npm run prisma:studio"
echo ""

echo "📋 LANGKAH 5: Start Development Server"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run:"
echo "  npm run dev"
echo ""
echo "Test API:"
echo "  GET  http://localhost:3000/api/theme"
echo "  POST http://localhost:3000/api/auth/signin"
echo ""

echo ""
echo "✅ Phase 1 Setup Complete!"
echo ""
echo "Next: Phase 2 - Admin Panel & Content Management"
echo ""
