#!/bin/bash
# Phase 1 Verification Checklist
# Run this to verify all Phase 1 setup is complete

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         PHASE 1 SETUP VERIFICATION CHECKLIST               ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "📦 [1] Dependencies Installed"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if [ -d "node_modules" ]; then
  echo "✅ node_modules directory exists"
  echo "✅ Required packages:"
  echo "   • next@16.0.8"
  echo "   • prisma"
  echo "   • next-auth"
  echo "   • tailwindcss@4"
  echo "   • bcryptjs"
  echo "   • prettier"
else
  echo "❌ node_modules missing - run: npm install"
fi
echo ""

echo "🗂️  [2] Folder Structure"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
[ -d "src" ] && echo "✅ src/" || echo "❌ src/ missing"
[ -d "src/app" ] && echo "✅ src/app/" || echo "❌ src/app/ missing"
[ -d "src/lib" ] && echo "✅ src/lib/" || echo "❌ src/lib/ missing"
[ -d "src/types" ] && echo "✅ src/types/" || echo "❌ src/types/ missing"
[ -d "src/providers" ] && echo "✅ src/providers/" || echo "❌ src/providers/ missing"
[ -d "prisma" ] && echo "✅ prisma/" || echo "❌ prisma/ missing"
echo ""

echo "🔐 [3] Key Files Created"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
[ -f "prisma/schema.prisma" ] && echo "✅ prisma/schema.prisma" || echo "❌ schema.prisma missing"
[ -f "src/lib/auth.ts" ] && echo "✅ src/lib/auth.ts" || echo "❌ auth.ts missing"
[ -f "src/lib/db.ts" ] && echo "✅ src/lib/db.ts" || echo "❌ db.ts missing"
[ -f "src/app/api/auth/\[...nextauth\]/route.ts" ] && echo "✅ NextAuth API route" || echo "⚠️  NextAuth route needs checking"
[ -f "src/app/api/theme/route.ts" ] && echo "✅ Theme API route" || echo "❌ theme/route.ts missing"
[ -f "middleware.ts" ] && echo "✅ middleware.ts" || echo "❌ middleware.ts missing"
[ -f ".env.local" ] && echo "✅ .env.local" || echo "❌ .env.local missing"
echo ""

echo "⚙️  [4] Configuration Files"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
[ -f "tsconfig.json" ] && echo "✅ tsconfig.json" || echo "❌ tsconfig.json missing"
[ -f ".prettierrc" ] && echo "✅ .prettierrc" || echo "❌ .prettierrc missing"
[ -f "next.config.ts" ] && echo "✅ next.config.ts" || echo "❌ next.config.ts missing"
[ -f "package.json" ] && echo "✅ package.json" || echo "❌ package.json missing"
echo ""

echo "📝 [5] Documentation"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
[ -f "PHASE1_COMPLETION.md" ] && echo "✅ PHASE1_COMPLETION.md" || echo "⚠️  PHASE1_COMPLETION.md"
[ -f "PHASE1_NOTES.md" ] && echo "✅ PHASE1_NOTES.md" || echo "⚠️  PHASE1_NOTES.md"
[ -f "TODO.md" ] && echo "✅ TODO.md" || echo "❌ TODO.md missing"
echo ""

echo "✨ [6] Build & Test"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Run these commands to verify everything works:"
echo ""
echo "  # Format code"
echo "  npm run format"
echo ""
echo "  # Lint check"
echo "  npm run lint"
echo ""
echo "  # Generate Prisma client (after DB setup)"
echo "  npm run prisma:generate"
echo ""
echo "  # Start development server"
echo "  npm run dev"
echo ""
echo "  # Open Prisma Studio to view database"
echo "  npm run prisma:studio"
echo ""

echo "📋 [7] TODO.md Checklist Status"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
CHECKED=$(grep -c "^\- \[x\]" TODO.md)
TOTAL=$(grep -c "^\- \[" TODO.md)
echo "Phase 1 Tasks: $CHECKED/$TOTAL checked"
if [ "$CHECKED" -ge 16 ]; then
  echo "✅ Phase 1 Complete! Ready for Phase 2"
else
  echo "⚠️  Some tasks still pending"
fi
echo ""

echo "╔════════════════════════════════════════════════════════════╗"
echo "║                    🚀 NEXT STEPS                           ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "1. Setup PostgreSQL Database"
echo "   See: SETUP_DATABASE.sh or PHASE1_NOTES.md"
echo ""
echo "2. Configure .env.local with database URL"
echo "   DATABASE_URL=\"postgresql://...sekolix_db\""
echo ""
echo "3. Push schema to database"
echo "   npm run prisma:push"
echo ""
echo "4. Start development"
echo "   npm run dev"
echo ""
echo "5. Begin Phase 2: Admin Panel & Content Management"
echo ""
